[package]
name = "tango-core"
version = "0.0.0"
edition = "2021"
license = "AGPL-3.0-or-later"
default-run = "tango-core"

[dependencies]
anyhow = "1.0"
env_logger = "0.9.0"
winit = { version = "0.26.1", features = ["serde"] }
cpal = "0.13.5"
zstd = "0.11.1"
lazy_static = "1.4.0"
log = "0.4"
tokio = { version = "1.15.0", features = ["full"] }
parking_lot = { version = "0.12.0" }
rand = "0.8.5"
sha3 = "0.10.1"
tokio-util = "0.7.1"
tokio-stream = "0.1.8"
subtle = "2.4"
rand_pcg = { version = "0.3.1", features = ["serde1"] }
serde = { version = "1.0", features = ["derive"] }
git-version = "0.3.5"
bincode = "1.3.3"
byteorder = "1.4.3"
time = { version = "0.3.9", features = ["formatting", "macros"] }
futures-util = "0.3.21"
clap = { version = "3.1", features = ["derive"] }
tango-protos = { path = "../tango-protos" }
mgba = { path = "../mgba" }
tempfile = "3.3.0"
shell-words = "1.1"
serde_json = "1.0"
url = "2.2"
serde_plain = "1.0"
egui = "0.17"
egui-winit = { version = "0.17", default-features = false }
datachannel-wrapper = { path = "../datachannel-wrapper" }
gilrs = "0.8"
tokio-tungstenite = { version = "0.17.1", features = ["native-tls"] }
prost = "0.10"
bytes = "1.1.0"
glutin = "0.28.0"
glow = "0.11"
egui_glow = "0.17"
glowfb = { path = "../glowfb" }

[build-dependencies]
winres = "0.1"
